# This config file provides parameter values for the instantiation of the Occlusion Dataset.

pickle_id: "processed_sdd"  # the name of the folder from which to load the base, preprocessed dataset.
sim_ids:                    # the name of the occlusion simulation folders to use to instantiate the occlusion simulation dataset.
  - "v3_161803399"
  - "v3_271828183"
  - "v3_314159265"
